#!/bin/bash

dev=`cat output | grep dev | awk -F"\"" '{print $2}'`
prod=`cat output | grep prod | awk -F"\"" '{print $2}'`

sed -i '2 i development ansible_host='$dev'' hosts
sed -i '5 i production ansible_host='$prod'' hosts
